"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
export function RatesManager({cameras,accessories,rates}:{cameras:any[];accessories:any[];rates:any[]}){
  const supabase=createClient();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const ref=String(f.get("asset")||"");const [type,id]=ref.split(":");setBusy(true);setMessage("");try{const row:any={daily_rate_inr:Number(f.get("daily")||0),weekly_rate_inr:Number(f.get("weekly")||0)||null,deposit_inr:Number(f.get("deposit")||0),notes:String(f.get("notes")||"").trim()||null};row[type==="camera"?"camera_id":"accessory_id"]=id;const {error}=await supabase.from("internal_rates").insert(row);if(error)throw error;location.reload();}catch(err){setMessage(err instanceof Error?err.message:"Unable to save rate.");setBusy(false);}}
  return <><form className="adminPanel formPanel" onSubmit={save}><h2>Add internal rate</h2><label>Equipment<select name="asset" required><option value="">Choose asset</option>{cameras.map(x=><option key={x.id} value={`camera:${x.id}`}>{x.camera_code} · {x.name}</option>)}{accessories.map(x=><option key={x.id} value={`accessory:${x.id}`}>{x.accessory_code} · {x.name}</option>)}</select></label><div className="formGrid"><label>Daily rate ₹<input name="daily" type="number" min="0" required/></label><label>Weekly rate ₹ <small>(optional)</small><input name="weekly" type="number" min="0"/></label></div><label>Deposit ₹<input name="deposit" type="number" min="0" defaultValue="0"/></label><label>Internal notes<input name="notes"/></label><button type="submit" className="button gold" disabled={busy}>{busy?"Saving rate…":"Save internal rate"}</button>{message&&<div className="errorBox" role="status">{message}</div>}</form>
  <div className="adminPanel"><h2>Rate card — staff only</h2>{rates.map((r:any)=><div className="bookingRow" key={r.id}><div><b>{r.cameras?.camera_code||r.accessories?.accessory_code} · {r.cameras?.name||r.accessories?.name}</b><span>Deposit ₹{Number(r.deposit_inr||0).toLocaleString("en-IN")}</span></div><strong>₹{Number(r.daily_rate_inr).toLocaleString("en-IN")}/day</strong></div>)}</div></>;
}
