"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

const local=(v:string)=>new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16);

export function BookingCorrectionPanel({booking}:{booking:any}){
  const supabase=createClient();const router=useRouter();
  const [open,setOpen]=useState(false),[operationalOpen,setOperationalOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const datesLocked=["checked_out","overdue","returned","closed"].includes(booking.status);
  const canCorrectCheckout=["checked_out","overdue","returned","closed"].includes(booking.status);
  const canCorrectReturn=["returned","closed"].includes(booking.status);

  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage("");try{const {error}=await supabase.rpc("correct_booking_details",{p_booking_id:booking.id,p_project_name:String(f.get("project")||"")||null,p_production_name:String(f.get("production")||"")||null,p_contact_name:String(f.get("contact")||"")||null,p_contact_phone:String(f.get("phone")||"")||null,p_start_at:datesLocked?booking.start_at:new Date(String(f.get("start_at"))).toISOString(),p_end_at:datesLocked?booking.end_at:new Date(String(f.get("end_at"))).toISOString(),p_pickup_location:String(f.get("pickup")||"")||null,p_return_location:String(f.get("return_location")||"")||null,p_operator_name:String(f.get("operator")||"")||null,p_notes:String(f.get("notes")||"")||null,p_reason:String(f.get("reason")||"")});if(error)throw error;setMessage("Booking correction saved and added to history.");setOpen(false);router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to correct booking.");}finally{setBusy(false);}}

  async function correctAsset(e:React.FormEvent<HTMLFormElement>,phase:"checkout"|"return",kind:"camera"|"accessory",assetId:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage("");try{const rpc=phase==="checkout"?"correct_checkout_asset":"correct_return_asset";const hours=kind==="camera"?Number(f.get("hours")||0):null;const {error}=await supabase.rpc(rpc,{p_booking_id:booking.id,p_kind:kind,p_asset_id:assetId,p_hours:hours,p_condition:String(f.get("condition")||"good"),p_reason:String(f.get("reason")||"")});if(error)throw error;setMessage(`${phase==="checkout"?"Checkout":"Return"} record corrected and added to history.`);router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to correct operational record.");}finally{setBusy(false);}}

  return <div className="adminPanel">
    <div className="panelHeading"><div><h2>Correction controls</h2><p>Use corrections instead of deleting/recreating records. Every correction requires a reason and is audit logged.</p></div><div className="panelActions"><button type="button" className="button ghost" onClick={()=>setOpen(!open)}>{open?"Close Details Editor":"Edit / Correct Booking"}</button>{canCorrectCheckout&&<button type="button" className="button ghost" onClick={()=>setOperationalOpen(!operationalOpen)}>{operationalOpen?"Close Operational Corrections":"Correct Checkout / Return"}</button>}</div></div>

    {open&&<form className="correctionPanel embedded" onSubmit={save}><div className="formGrid"><label>Production<input name="production" defaultValue={booking.production_name||""}/></label><label>Project<input name="project" defaultValue={booking.project_name||""}/></label></div><div className="formGrid"><label>Contact<input name="contact" defaultValue={booking.contact_name||""}/></label><label>Phone<input name="phone" defaultValue={booking.contact_phone||""}/></label></div><div className="formGrid"><label>Start<input name="start_at" type="datetime-local" defaultValue={local(booking.start_at)} disabled={datesLocked}/></label><label>Return<input name="end_at" type="datetime-local" defaultValue={local(booking.end_at)} disabled={datesLocked}/></label></div>{datesLocked&&<p className="formNote">Rental dates are locked after checkout so historical availability is not rewritten.</p>}<div className="formGrid"><label>Pickup location<input name="pickup" defaultValue={booking.pickup_location||""}/></label><label>Return location<input name="return_location" defaultValue={booking.return_location||""}/></label></div><label>Operator / responsible person<input name="operator" defaultValue={booking.operator_name||""}/></label><label>Notes<textarea name="notes" defaultValue={booking.notes||""}/></label><label>Reason for correction<input required minLength={4} name="reason" placeholder="Example: customer phone entered incorrectly"/></label><div className="panelActions"><button type="button" className="button ghost" onClick={()=>setOpen(false)}>Cancel</button><button type="submit" className="button gold" disabled={busy}>{busy?"Saving…":"Save Correction"}</button></div></form>}

    {operationalOpen&&<div className="operationalCorrectionGrid">
      {(booking.booking_cameras||[]).map((bc:any)=><div className="correctionPanel" key={`cam-${bc.id}`}><div><h3>{bc.cameras?.camera_code} · {bc.cameras?.name}</h3><p>Correct meter hours or condition without deleting checkout/return history.</p></div>{canCorrectCheckout&&<form className="assetCorrectionForm" onSubmit={e=>void correctAsset(e,"checkout","camera",bc.camera_id)}><b>Checkout record</b><div className="formGrid"><label>Checkout hours<input required name="hours" type="number" min="0" step="0.1" defaultValue={bc.checkout_hours??0}/></label><label>Condition out<select name="condition" defaultValue={bc.condition_out||"good"}><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></select></label></div><label>Correction reason<input required minLength={4} name="reason" placeholder="Why is this being corrected?"/></label><button type="submit" className="button ghost" disabled={busy}>Correct Checkout</button></form>}{canCorrectReturn&&<form className="assetCorrectionForm" onSubmit={e=>void correctAsset(e,"return","camera",bc.camera_id)}><b>Return record</b><div className="formGrid"><label>Return hours<input required name="hours" type="number" min={bc.checkout_hours||0} step="0.1" defaultValue={bc.return_hours??bc.checkout_hours??0}/></label><label>Condition in<select name="condition" defaultValue={bc.condition_in||"good"}><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option><option value="missing">Missing</option></select></label></div><label>Correction reason<input required minLength={4} name="reason" placeholder="Why is this being corrected?"/></label><button type="submit" className="button ghost" disabled={busy}>Correct Return</button></form>}</div>)}
      {(booking.booking_accessories||[]).map((ba:any)=><div className="correctionPanel" key={`acc-${ba.id}`}><div><h3>{ba.accessories?.accessory_code} · {ba.accessories?.name}</h3><p>Correct accessory condition with a traceable reason.</p></div>{canCorrectCheckout&&<form className="assetCorrectionForm" onSubmit={e=>void correctAsset(e,"checkout","accessory",ba.accessory_id)}><b>Checkout record</b><label>Condition out<select name="condition" defaultValue={ba.condition_out||"good"}><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option></select></label><label>Correction reason<input required minLength={4} name="reason" placeholder="Why is this being corrected?"/></label><button type="submit" className="button ghost" disabled={busy}>Correct Checkout</button></form>}{canCorrectReturn&&<form className="assetCorrectionForm" onSubmit={e=>void correctAsset(e,"return","accessory",ba.accessory_id)}><b>Return record</b><label>Condition in<select name="condition" defaultValue={ba.condition_in||"good"}><option value="good">Good</option><option value="fair">Fair</option><option value="damaged">Damaged</option><option value="missing">Missing</option></select></label><label>Correction reason<input required minLength={4} name="reason" placeholder="Why is this being corrected?"/></label><button type="submit" className="button ghost" disabled={busy}>Correct Return</button></form>}</div>)}
    </div>}
    {message&&<div className={message.includes("corrected")||message.includes("saved")?"successBox":"errorBox"}>{message}</div>}
  </div>;
}
