"use client";import {useState} from "react";import {createClient} from "@/lib/supabase/client";import {AssetScanner} from "@/components/AssetScanner";
export function OperationsManager({bookings,userId}:{bookings:any[];userId:string}){
 const supabase=createClient();const [bookingId,setBookingId]=useState("");const [scanned,setScanned]=useState<string[]>([]);const [msg,setMsg]=useState("");const b=bookings.find(x=>x.id===bookingId);
 const expected=(b?.booking_cameras||[]).map((x:any)=>x.cameras?.qr_code).filter(Boolean);
 async function uploadPhoto(file:File,bookingId:string,cameraId:string,type:string,hours?:number){const path=`${bookingId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const up=await supabase.storage.from("rental-evidence").upload(path,file);if(up.error)throw up.error;await supabase.from("evidence").insert({booking_id:bookingId,camera_id:cameraId,evidence_type:type,file_path:path,camera_hours:hours||null,captured_by:userId});}
 async function checkout(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!b)return;const missing=expected.filter((x:string)=>!scanned.includes(x));if(missing.length)return setMsg(`Missing scans: ${missing.join(", ")}`);const f=new FormData(e.currentTarget);for(const bc of b.booking_cameras){const hours=Number(f.get(`hours-${bc.camera_id}`)||0);const cond=String(f.get(`condition-${bc.camera_id}`)||"good");await supabase.from("booking_cameras").update({checkout_hours:hours,condition_out:cond}).eq("id",bc.id);await supabase.from("cameras").update({status:"out",current_hours:hours}).eq("id",bc.camera_id);const file=f.get(`photo-${bc.camera_id}`);if(file instanceof File&&file.size)await uploadPhoto(file,b.id,bc.camera_id,"checkout_hours",hours);}await supabase.from("bookings").update({status:"checked_out",checked_out_at:new Date().toISOString()}).eq("id",b.id);setMsg("Checkout completed.");setTimeout(()=>location.reload(),700);}
 async function returnRental(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!b)return;const f=new FormData(e.currentTarget);let damage=Number(f.get("damage")||0),late=Number(f.get("late")||0),other=Number(f.get("other")||0),paid=Number(f.get("paid")||0);for(const bc of b.booking_cameras){const hours=Number(f.get(`return-hours-${bc.camera_id}`)||0);const cond=String(f.get(`return-condition-${bc.camera_id}`)||"good");await supabase.from("booking_cameras").update({return_hours:hours,condition_in:cond}).eq("id",bc.id);await supabase.from("cameras").update({status:"available",current_hours:hours}).eq("id",bc.camera_id);const file=f.get(`return-photo-${bc.camera_id}`);if(file instanceof File&&file.size)await uploadPhoto(file,b.id,bc.camera_id,"return_hours",hours);}const rental=Number(b.quoted_total_inr||0);const balance=Math.max(0,rental+damage+late+other-paid);await supabase.from("bookings").update({status:"returned",returned_at:new Date().toISOString(),amount_received_inr:paid,payment_status:balance>0?"partial":"paid"}).eq("id",b.id);await supabase.from("receipts").upsert({booking_id:b.id,customer_id:b.customer_id,rental_amount_inr:rental,damage_charges_inr:damage,late_charges_inr:late,other_charges_inr:other,amount_paid_inr:paid,balance_inr:balance,payment_method:String(f.get("method")||""),payment_reference:String(f.get("reference")||""),return_notes:String(f.get("notes")||""),issued_by:userId},{onConflict:"booking_id"});setMsg("Return completed and receipt generated.");setTimeout(()=>location.href="/admin/receipts",900);}
 return <><div className="adminPanel formPanel"><h2>Select active booking</h2><select value={bookingId} onChange={e=>{setBookingId(e.target.value);setScanned([]);setMsg("")}}><option value="">Choose booking</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.booking_code} · {b.production_name||"Client"} · {b.status}</option>)}</select></div>
 {b&&["reserved","confirmed","preparing"].includes(b.status)&&<form className="adminPanel formPanel" onSubmit={checkout}><h2>QR checkout</h2><AssetScanner onCode={code=>setScanned(s=>s.includes(code)?s:[...s,code])}/><div className="scanSummary"><b>Expected {expected.length}</b><span>Scanned {scanned.length}</span></div>{b.booking_cameras.map((bc:any)=><div className="assetOperation" key={bc.id}><h3>{bc.cameras.camera_code} · {bc.cameras.name}</h3><span>QR {bc.cameras.qr_code}</span><div className="formGrid"><input required name={`hours-${bc.camera_id}`} type="number" step=".1" placeholder="Camera hours"/><select name={`condition-${bc.camera_id}`}><option>good</option><option>fair</option><option>damaged</option></select></div><label>Checkout proof photo<input required name={`photo-${bc.camera_id}`} type="file" accept="image/*" capture="environment"/></label></div>)}<button className="button gold">Complete checkout</button></form>}
 {b&&["checked_out","overdue"].includes(b.status)&&<form className="adminPanel formPanel" onSubmit={returnRental}><h2>Return & final receipt</h2>{b.booking_cameras.map((bc:any)=><div className="assetOperation" key={bc.id}><h3>{bc.cameras.camera_code} · {bc.cameras.name}</h3><div className="formGrid"><input required name={`return-hours-${bc.camera_id}`} type="number" step=".1" min={bc.checkout_hours||0} placeholder="Return hours"/><select name={`return-condition-${bc.camera_id}`}><option>good</option><option>fair</option><option>damaged</option><option>missing</option></select></div><label>Return proof photo<input required name={`return-photo-${bc.camera_id}`} type="file" accept="image/*" capture="environment"/></label></div>)}<div className="formGrid"><input name="damage" type="number" placeholder="Damage charge ₹"/><input name="late" type="number" placeholder="Late charge ₹"/></div><div className="formGrid"><input name="other" type="number" placeholder="Other charge ₹"/><input name="paid" type="number" placeholder="Total amount paid ₹"/></div><div className="formGrid"><select name="method"><option value="">Payment method</option><option>UPI</option><option>Bank Transfer</option><option>Cash</option><option>Card</option></select><input name="reference" placeholder="Payment reference"/></div><textarea name="notes" placeholder="Return notes / damage notes"/><button className="button gold">Return equipment & generate receipt</button></form>}
 {msg&&<div className={msg.includes("completed")||msg.includes("generated")?"successBox":"errorBox"}>{msg}</div>}</>
}
