import Link from "next/link";
import { EquipmentCard } from "@/components/EquipmentCard";
import { address, equipment, phones } from "@/lib/data";
const categories=[...new Set(equipment.map(x=>x.category))];
export default function Home(){return <>
<section className="hero"><div className="heroContent"><div className="eyebrow">SRI CINE HUB PVT. LTD. · CHENNAI</div><h1>Camera rental.<br/><span>Lights. Grip. Post.</span></h1><p>One-stop production support for filmmakers—from cinema cameras and lenses to lighting, grip, transport, gensets and post-production studios.</p><div className="actions"><Link className="button gold" href="/request-quote">Check availability</Link><Link className="button ghost" href="/equipment">Browse equipment</Link></div></div><div className="heroMark"><img src="/sri-cine-hub-logo.jpg" alt="Sri Cine Hub"/></div></section>
<section className="section"><div className="sectionHeading"><div><div className="eyebrow">PRODUCTION INVENTORY</div><h2>Build the package your shoot needs.</h2></div><Link className="textLink" href="/equipment">View full inventory →</Link></div><div className="categoryGrid">{categories.map(cat=><article className="categoryCard" key={cat}><span>{cat}</span><strong>{equipment.filter(x=>x.category===cat).length}</strong><p>Request exact model and date availability.</p></article>)}</div></section>
<section className="section"><div className="sectionHeading"><div><div className="eyebrow">FEATURED</div><h2>Core production services.</h2></div></div><div className="equipmentGrid">{equipment.filter(x=>x.featured).map(i=><EquipmentCard item={i} key={i.id}/>)}</div></section>
<section className="section split"><div><div className="eyebrow">RENTAL WORKFLOW</div><h2>Reservations are date-based—not just “available” or “out.”</h2><p className="muted">A camera can be checked out today and still be reserved for a future non-overlapping period. Staff will confirm every quote before the reservation is locked.</p><Link className="button gold" href="/request-quote">Request a quote</Link></div><div className="featureList"><div><b>01</b><span>Request dates & equipment</span></div><div><b>02</b><span>Staff checks conflicts</span></div><div><b>03</b><span>Quote & reservation confirmation</span></div><div><b>04</b><span>Checkout, meter proof & return</span></div></div></section>
<section className="contactBand"><div><div className="eyebrow">CHENNAI</div><h2>Talk to the rental team.</h2><p>{address}</p></div><div className="phoneList">{phones.map(p=><a key={p} href={`tel:${p.replaceAll(" ","")}`}>{p}</a>)}</div></section>
</>}
