"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
type Payment={id:string;amount_inr:number;method:string|null;reference:string|null;received_at:string;notes:string|null;transaction_type:string;status:string;reversed_payment_id:string|null;correction_reason:string|null};
type Audit={id:number;action:string;created_at:string;old_data:any;new_data:any};

export function ReceiptCorrectionPanel({receipt,payments,audit}:{receipt:any;payments:Payment[];audit:Audit[]}){
  const supabase=createClient();const router=useRouter();
  const [mode,setMode]=useState<"payment"|"charges"|"history"|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const posted=payments.filter(p=>p.status==="posted");
  const signed=(p:Payment)=>["refund","reversal"].includes(p.transaction_type)?-Number(p.amount_inr):Number(p.amount_inr);
  const paid=useMemo(()=>posted.reduce((s,p)=>s+signed(p),0),[posted]);

  async function addPayment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage("");try{const amount=Number(f.get("amount")||0);const {error}=await supabase.rpc("add_booking_payment",{p_booking_id:receipt.booking_id,p_amount_inr:amount,p_method:String(f.get("method")||"")||null,p_reference:String(f.get("reference")||"")||null,p_notes:String(f.get("notes")||"")||null,p_received_at:new Date(String(f.get("received_at")||new Date().toISOString())).toISOString()});if(error)throw error;setMessage(`Payment ${money(amount)} added.`);setMode(null);router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to add payment.");}finally{setBusy(false);}}
  async function reversePayment(p:Payment){const reason=prompt(`Reason for reversing ${money(p.amount_inr)}?`);if(!reason)return;setBusy(true);setMessage("");try{const {error}=await supabase.rpc("reverse_booking_payment",{p_payment_id:p.id,p_reason:reason});if(error)throw error;setMessage("Payment reversed. The original transaction remains in history.");router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to reverse payment.");}finally{setBusy(false);}}
  async function correctCharges(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage("");try{const {error}=await supabase.rpc("correct_receipt_charges",{p_receipt_id:receipt.id,p_damage_inr:Number(f.get("damage")||0),p_late_inr:Number(f.get("late")||0),p_other_inr:Number(f.get("other")||0),p_discount_inr:Number(f.get("discount")||0),p_notes:String(f.get("notes")||"")||null,p_reason:String(f.get("reason")||"")});if(error)throw error;setMessage("Receipt charges corrected and recorded in history.");setMode(null);router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to correct receipt.");}finally{setBusy(false);}}

  return <div className="receiptCorrectionShell printHide">
    <div className="correctionActionBar">
      <button type="button" className="button gold" onClick={()=>setMode(mode==="payment"?null:"payment")}>+ Add Payment</button>
      <button type="button" className="button ghost" onClick={()=>setMode(mode==="charges"?null:"charges")}>Correct Charges</button>
      <button type="button" className="button ghost" onClick={()=>setMode(mode==="history"?null:"history")}>History ({payments.length+audit.length})</button>
      <a className="button ghost" href={`/admin/bookings/${receipt.booking_id}`}>← Booking</a>
      <div className="financialQuick"><span>Paid</span><b>{money(paid)}</b><span>Balance</span><b>{money(receipt.balance_inr)}</b></div>
    </div>
    {mode==="payment"&&<form className="correctionPanel" onSubmit={addPayment}><div><h3>Add payment</h3><p>Payments are transactions. Adding a later payment updates Paid and Balance without rewriting the original receipt history.</p></div><div className="formGrid"><label>Amount ₹<input required name="amount" type="number" min="0.01" step="0.01" defaultValue={Number(receipt.balance_inr||0)||""}/></label><label>Payment method<select name="method" defaultValue="UPI"><option>UPI</option><option>Bank Transfer</option><option>Cash</option><option>Card</option><option>Other</option></select></label></div><div className="formGrid"><label>Reference<input name="reference" placeholder="UPI / bank / card reference"/></label><label>Received at<input name="received_at" type="datetime-local" defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></label></div><label>Notes<textarea name="notes" placeholder="Optional payment note"/></label><div className="panelActions"><button type="button" className="button ghost" onClick={()=>setMode(null)}>Cancel</button><button type="submit" className="button gold" disabled={busy}>{busy?"Saving…":"Add Payment"}</button></div></form>}
    {mode==="charges"&&<form className="correctionPanel" onSubmit={correctCharges}><div><h3>Correct receipt charges</h3><p>This does not silently overwrite history. The before/after values and correction reason are stored in the audit trail.</p></div><div className="formGrid"><label>Damage charges ₹<input name="damage" type="number" min="0" defaultValue={receipt.damage_charges_inr||0}/></label><label>Late charges ₹<input name="late" type="number" min="0" defaultValue={receipt.late_charges_inr||0}/></label></div><div className="formGrid"><label>Other charges ₹<input name="other" type="number" min="0" defaultValue={receipt.other_charges_inr||0}/></label><label>Discount ₹<input name="discount" type="number" min="0" defaultValue={receipt.discount_inr||0}/></label></div><label>Return / charge notes<textarea name="notes" defaultValue={receipt.return_notes||""}/></label><label>Reason for correction<input required name="reason" minLength={4} placeholder="Example: damage charge entered incorrectly"/></label><div className="panelActions"><button type="button" className="button ghost" onClick={()=>setMode(null)}>Cancel</button><button type="submit" className="button gold" disabled={busy}>{busy?"Saving…":"Save Correction"}</button></div></form>}
    {mode==="history"&&<div className="correctionPanel"><h3>Payment & correction history</h3><div className="activityTimeline">{payments.map(p=><div className="activityRow" key={`p-${p.id}`}><div><b>{p.transaction_type==="reversal"?"Payment reversal":"Payment"} · {money(signed(p))}</b><span>{new Date(p.received_at).toLocaleString("en-IN")} · {p.method||"Method not specified"}{p.reference?` · ${p.reference}`:""}</span>{p.correction_reason&&<small>Reason: {p.correction_reason}</small>}</div>{p.transaction_type==="payment"&&!payments.some(x=>x.reversed_payment_id===p.id&&x.status==="posted")&&<button type="button" className="button ghost dangerButton compactButton" disabled={busy} onClick={()=>void reversePayment(p)}>Reverse</button>}</div>)}{audit.map(a=><div className="activityRow" key={`a-${a.id}`}><div><b>{a.action.replaceAll("_"," ")}</b><span>{new Date(a.created_at).toLocaleString("en-IN")}</span>{a.new_data?.reason&&<small>Reason: {a.new_data.reason}</small>}</div></div>)}{!payments.length&&!audit.length&&<div className="formNote">No history yet.</div>}</div></div>}
    {message&&<div className={message.toLowerCase().includes("unable")||message.toLowerCase().includes("required")?"errorBox":"successBox"}>{message}</div>}
  </div>;
}
