"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {DocumentActions} from "@/components/DocumentActions";
export function SupplierRFQActions({id,code,status,supplierName}:{id:string;code:string;status:string;supplierName:string}){
  const supabase=createClient();const router=useRouter();const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState("");
  async function mark(next:string){setBusy(next);setMessage("");try{const {error}=await supabase.from("supplier_rfqs").update({status:next,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;setMessage(`Supplier RFQ marked ${next.replaceAll("_"," ")}.`);router.refresh();}catch(err){setMessage(err instanceof Error?err.message:"Unable to update supplier RFQ.");}finally{setBusy(null);}}
  return <><div className="documentStatusLine printHide"><span>STATUS</span><b className={`workflowBadge ${status}`}>{status.replaceAll("_"," ")}</b></div><DocumentActions editHref="/admin/supplier-rfqs/new" downloadHref={`/api/documents/supplier-rfq/${id}/pdf`} fileName={`SriCineHub-${code}.pdf`} whatsappText={`Hi ${supplierName}, please find Sri Cine Hub ${code}. Kindly confirm equipment availability and your best rental rates.`}>{(status==="generated"||status==="draft")&&<button type="button" className="button gold" disabled={!!busy} onClick={()=>mark("sent")}>{busy==="sent"?"Marking Sent…":"Mark Sent"}</button>}{status==="sent"&&<button type="button" className="button gold" disabled={!!busy} onClick={()=>mark("quote_received")}>{busy==="quote_received"?"Updating…":"Quote Received"}</button>}{status==="quote_received"&&<><button type="button" className="button ghost dangerButton" disabled={!!busy} onClick={()=>mark("declined")}>{busy==="declined"?"Declining…":"Decline"}</button><button type="button" className="button gold" disabled={!!busy} onClick={()=>mark("confirmed")}>{busy==="confirmed"?"Confirming…":"Confirm Supplier"}</button></>}</DocumentActions>{message&&<div className={message.toLowerCase().includes("unable")?"errorBox printHide":"successBox printHide"} role="status">{message}</div>}</>;
}
