import {notFound} from "next/navigation";import {requireStaff} from "@/lib/auth";import {QuotationDocumentActions} from "./QuotationDocumentActions";
const money=(n:any)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
function dateRange(request:any){if(!request?.start_at&&!request?.end_at)return "Dates not entered";const s=request?.start_at?new Date(request.start_at).toLocaleString("en-IN"):"Start not set";const e=request?.end_at?new Date(request.end_at).toLocaleString("en-IN"):"Return not set";return `${s} → ${e}`;}
export default async function PrintableQuotation({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{generated?:string}>}){const {id}=await params;const query=await searchParams;const {supabase}=await requireStaff();const [{data:q},{data:items},{data:req}]=await Promise.all([supabase.from("quotations").select("*,customers(*)").eq("id",id).single(),supabase.from("quotation_items").select("*").eq("quotation_id",id).order("sort_order"),supabase.from("quotations").select("quote_request_id,quote_requests(*)").eq("id",id).single()]);if(!q)notFound();const request=(req as any)?.quote_requests;const customerName=q.customers?.company_name||q.customers?.name||request?.company_name||request?.name||"Customer";const groups=new Map<string,any[]>();for(const item of items||[]){const section=item.section_name||"General";if(!groups.has(section))groups.set(section,[]);groups.get(section)!.push(item);}let serial=0;
 return <main className="printDocument">{query.generated==="1"&&<div className="documentSuccessBanner printHide">✓ Quotation {q.quotation_code} generated. The PDF actions below work independently from the browser print dialog.</div>}<QuotationDocumentActions quotationId={id} quotationCode={q.quotation_code} status={q.status} customerName={customerName}/><section className="quotationPaper"><header className="quotationHeader"><div><h1>SRI CINE HUB PVT. LTD.</h1><p>Camera Rental · Lenses · Lights · Grip · Transport · Production Services</p></div><div className="quoteNumber"><span>QUOTATION</span><b>{q.quotation_code}</b><small>Date: {new Date(q.created_at).toLocaleDateString("en-IN")}</small><small>Valid until: {q.valid_until||"—"}</small></div></header><div className="quotationParties"><div><span>Customer</span><b>{customerName}</b><p>{q.customers?.name||request?.name||""}</p><p>{q.customers?.phone||request?.phone||""}</p><p>{q.customers?.email||request?.email||""}</p></div><div><span>Project / Rental</span><b>{request?.project_name||"Project not entered"}</b><p>{dateRange(request)}</p></div></div>
 <table className="printQuoteTable groupedQuoteTable"><thead><tr><th>S. No</th><th>Description</th><th>Qty</th><th>Days</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{Array.from(groups.entries()).map(([section,sectionItems])=><FragmentSection key={section} section={section} items={sectionItems} next={()=>++serial}/>)}</tbody><tfoot><tr className="printSubtotalRow"><td colSpan={5}>Subtotal</td><td>{money(q.subtotal_inr)}</td></tr>{Number(q.discount_inr)>0&&<tr className="printAdjRow"><td colSpan={5}>Discount</td><td>- {money(q.discount_inr)}</td></tr>}{Number(q.tax_inr)>0&&<tr className="printAdjRow"><td colSpan={5}>Tax</td><td>{money(q.tax_inr)}</td></tr>}{Number(q.other_charges_inr)>0&&<tr className="printAdjRow"><td colSpan={5}>Other charges</td><td>{money(q.other_charges_inr)}</td></tr>}<tr className="printGrandTotalRow"><td colSpan={5}>Grand Total</td><td>{money(q.total_inr)}</td></tr></tfoot></table>
 {(items||[]).length===0&&<div className="emptyQuotationDocument">No quotation items have been added yet.</div>}{q.customer_notes&&<div className="quoteTerms"><h3>Notes / Terms</h3><p>{q.customer_notes}</p></div>}<footer className="quotationFooter"><b>SRI CINE HUB PVT. LTD.</b><span>Chennai · Camera Rental & Production Services</span></footer></section></main>;
}
function FragmentSection({section,items,next}:{section:string;items:any[];next:()=>number}){return <><tr className="quoteSectionRow"><td colSpan={6}>{section}</td></tr>{items.map((x:any)=><tr key={x.id}><td>{next()}</td><td><b>{x.description||x.requested_description||"Untitled item"}</b></td><td>{Number(x.quantity||0)}</td><td>{Number(x.rental_days||0)}</td><td>{money(x.unit_rate_inr)}</td><td>{money(x.line_total_inr)}</td></tr>)}</>;}
