"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
export function KitManager({kits,cameras,accessories}:{kits:any[];cameras:any[];accessories:any[]}){
  const supabase=createClient();const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);setMessage("");try{const {data:k,error}=await supabase.from("equipment_kits").insert({kit_code:String(f.get("code")||"").trim().toUpperCase(),name:String(f.get("name")||"").trim(),description:String(f.get("description")||"").trim()||null,internal_daily_rate_inr:Number(f.get("rate")||0)}).select("id").single();if(error)throw error;const rows=selected.map(s=>{const [t,id]=s.split(":");return {kit_id:k.id,camera_id:t==="camera"?id:null,accessory_id:t==="accessory"?id:null}});if(rows.length){const x=await supabase.from("equipment_kit_items").insert(rows);if(x.error)throw x.error;}location.reload();}catch(err){setMessage(err instanceof Error?err.message:"Unable to create kit.");setBusy(false);}}
  const assets=[...cameras.map(x=>({key:`camera:${x.id}`,label:`${x.camera_code} · ${x.name}`})),...accessories.map(x=>({key:`accessory:${x.id}`,label:`${x.accessory_code} · ${x.name}`}))];
  return <><form className="adminPanel formPanel" onSubmit={create}><h2>Create equipment kit</h2><div className="formGrid"><label>Kit code<input name="code" required placeholder="KIT-A35-01"/></label><label>Kit name<input name="name" required placeholder="ALEXA 35 Full Kit"/></label></div><label>Internal kit daily rate ₹<input name="rate" type="number" min="0" defaultValue="0"/></label><label>Package description<textarea name="description"/></label><fieldset className="assetChecklistFieldset"><legend>Tracked kit items</legend><div className="assetChecklist">{assets.map(a=><label key={a.key}><input type="checkbox" checked={selected.includes(a.key)} onChange={e=>setSelected(e.target.checked?[...selected,a.key]:selected.filter(x=>x!==a.key))}/>{a.label}</label>)}</div></fieldset><button type="submit" className="button gold" disabled={busy}>{busy?"Creating kit…":"Create kit"}</button>{message&&<div className="errorBox" role="status">{message}</div>}</form>
  <div className="adminPanel"><h2>Active kits</h2>{kits.length?kits.map(k=><div className="bookingRow" key={k.id}><div><b>{k.kit_code} · {k.name}</b><span>{k.equipment_kit_items?.length||0} tracked items</span></div><strong>₹{Number(k.internal_daily_rate_inr||0).toLocaleString("en-IN")}/day</strong></div>):<p>No kits yet.</p>}</div></>;
}
