"use client";
import {useMemo,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "@/lib/supabase/client";
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export function SupplierManager({suppliers,items,catalog}:any){
 const supabase=createClient();const router=useRouter();const [selected,setSelected]=useState<string>(suppliers[0]?.id||"");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [search,setSearch]=useState("");
 const supplier=suppliers.find((x:any)=>x.id===selected);const supplierItems=items.filter((x:any)=>x.supplier_id===selected);const filtered=suppliers.filter((x:any)=>`${x.company_name} ${x.city||""} ${x.contact_name||""}`.toLowerCase().includes(search.toLowerCase()));
 async function addSupplier(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{const f=new FormData(e.currentTarget);const {data,error}=await supabase.from("suppliers").insert({company_name:String(f.get("company")||"").trim(),contact_name:String(f.get("contact")||"").trim()||null,phone:String(f.get("phone")||"").trim()||null,whatsapp:String(f.get("whatsapp")||"").trim()||null,email:String(f.get("email")||"").trim()||null,city:String(f.get("city")||"").trim()||null,state:String(f.get("state")||"").trim()||null,notes:String(f.get("notes")||"").trim()||null}).select("id").single();if(error)throw error;setSelected(data.id);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to create supplier.");}finally{setBusy(false);}}
 async function addCatalogModel(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{const f=new FormData(e.currentTarget);const {error}=await supabase.from("master_equipment_catalog").insert({canonical_name:String(f.get("name")||"").trim(),category:String(f.get("category")||"Other").trim()||"Other",manufacturer:String(f.get("manufacturer")||"").trim()||null,model:String(f.get("model")||"").trim()||null});if(error)throw error;router.refresh();(e.currentTarget as HTMLFormElement).reset();}catch(e){setMessage(e instanceof Error?e.message:"Unable to add equipment model.");}finally{setBusy(false);}}
 async function addSupplierItem(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setMessage("");try{const f=new FormData(e.currentTarget);const catalogId=String(f.get("catalog")||"")||null;const master=catalog.find((x:any)=>x.id===catalogId);const name=String(f.get("name")||"").trim()||master?.canonical_name||"Supplier item";const category=String(f.get("category")||"").trim()||master?.category||"Other";const {error}=await supabase.from("supplier_catalog_items").insert({supplier_id:selected,catalog_item_id:catalogId,supplier_item_name:name,category,quantity_available:Number(f.get("qty")||1),default_cost_inr:Number(f.get("cost")||0),rate_basis:String(f.get("basis")||"daily"),location:String(f.get("location")||"").trim()||supplier?.city||null,availability_notes:String(f.get("availability")||"").trim()||null});if(error)throw error;router.refresh();(e.currentTarget as HTMLFormElement).reset();}catch(e){setMessage(e instanceof Error?e.message:"Unable to add supplier item.");}finally{setBusy(false);}}
 async function toggleSupplier(id:string,current:boolean){setBusy(true);const {error}=await supabase.from("suppliers").update({is_active:!current,updated_at:new Date().toISOString()}).eq("id",id);if(error)setMessage(error.message);else router.refresh();setBusy(false);}
 async function removeItem(id:string){if(!confirm("Remove this supplier catalog item?"))return;setBusy(true);const {error}=await supabase.from("supplier_catalog_items").delete().eq("id",id);if(error)setMessage(error.message);else router.refresh();setBusy(false);}
 return <>
  <div className="supplierMetricGrid"><div><span>Suppliers</span><b>{suppliers.length}</b></div><div><span>Supplier equipment</span><b>{items.length}</b></div><div><span>Master catalog</span><b>{catalog.length}</b></div></div>
  <div className="supplierWorkspace">
   <aside className="supplierListPanel"><div className="supplierListHead"><h2>Suppliers</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search supplier…"/></div><div className="supplierList">{filtered.map((s:any)=><button type="button" key={s.id} className={selected===s.id?"active":""} onClick={()=>setSelected(s.id)}><div><b>{s.company_name}</b><span>{[s.city,s.contact_name].filter(Boolean).join(" · ")||"No contact details"}</span></div><em>{items.filter((x:any)=>x.supplier_id===s.id).length} items</em></button>)}</div><details className="supplierAddDetails"><summary>+ Add Supplier</summary><form onSubmit={addSupplier}><input required name="company" placeholder="Company name"/><div className="formGrid"><input name="contact" placeholder="Contact person"/><input name="phone" placeholder="Phone"/></div><div className="formGrid"><input name="whatsapp" placeholder="WhatsApp"/><input name="email" placeholder="Email"/></div><div className="formGrid"><input name="city" placeholder="City"/><input name="state" placeholder="State"/></div><textarea name="notes" placeholder="Notes"/><button className="button gold" disabled={busy}>Add Supplier</button></form></details></aside>
   <section className="supplierDetailPanel">{supplier?<><div className="supplierTitle"><div><span>{supplier.supplier_code}</span><h2>{supplier.company_name}</h2><p>{[supplier.contact_name,supplier.phone,supplier.city].filter(Boolean).join(" · ")||"Supplier profile"}</p></div><button type="button" className="button ghost" disabled={busy} onClick={()=>toggleSupplier(supplier.id,supplier.is_active)}>{supplier.is_active?"Active":"Inactive"}</button></div>
    <div className="supplierCatalogTable"><div className="supplierCatalogHeader"><span>Equipment</span><span>Qty</span><span>Our Cost</span><span>Basis</span><span></span></div>{supplierItems.length?supplierItems.map((x:any)=><div className="supplierCatalogRow" key={x.id}><div><b>{x.supplier_item_name}</b><span>{x.category}{x.location?` · ${x.location}`:""}</span></div><span>{Number(x.quantity_available||0)}</span><strong>{money(x.default_cost_inr)}</strong><span>{x.rate_basis}</span><button className="iconButton danger" type="button" onClick={()=>removeItem(x.id)}>×</button></div>):<div className="supplierEmpty">No equipment added to this supplier yet.</div>}</div>
    <details className="supplierCatalogAdd" open={supplierItems.length===0}><summary>+ Add Equipment to {supplier.company_name}</summary><form onSubmit={addSupplierItem}><label>Match master equipment<select name="catalog" defaultValue=""><option value="">No master match / custom item</option>{catalog.map((x:any)=><option value={x.id} key={x.id}>{x.category} · {x.canonical_name}</option>)}</select></label><div className="formGrid"><label>Supplier item name<input name="name" placeholder="Can be left blank when master item is selected"/></label><label>Category<input name="category" placeholder="Camera, Lenses, Lights…"/></label></div><div className="formGrid"><label>Available quantity<input name="qty" type="number" min="0" step="1" defaultValue="1"/></label><label>Normal supplier cost<input name="cost" type="number" min="0" defaultValue="0"/></label></div><div className="formGrid"><label>Cost basis<select name="basis" defaultValue="daily"><option value="hourly">Hourly</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="flat">Flat</option></select></label><label>Location<input name="location" placeholder={supplier.city||"Location"}/></label></div><label>Availability note<input name="availability" placeholder="Optional - call before confirming, available weekends, etc."/></label><button className="button gold" disabled={busy}>Add to Supplier Catalog</button></form></details>
   </>:<div className="supplierEmpty">Add or select a supplier.</div>}</section>
  </div>
  <details className="masterCatalogQuickAdd"><summary>+ Add New Equipment Model to Master Catalog</summary><form onSubmit={addCatalogModel}><div className="formGrid"><label>Canonical equipment name<input required name="name" placeholder="Cooke S7/i FF Lens Set"/></label><label>Category<input required name="category" placeholder="Lenses"/></label></div><div className="formGrid"><label>Manufacturer<input name="manufacturer"/></label><label>Model<input name="model"/></label></div><button className="button gold" disabled={busy}>Add Master Equipment</button></form></details>
  {message&&<div className="errorBox">{message}</div>}
 </>;
}
