"use client";
import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Pick={key:string;supplier_catalog_item_id:string|null;catalog_item_id:string|null;section_name:string;description:string;quantity:number;rental_days:number};
export function SupplierRFQBuilder({suppliers,supplierItems,quoteRequests}:any){
  const supabase=createClient();const [supplierId,setSupplierId]=useState("");const [requestId,setRequestId]=useState("");const [search,setSearch]=useState("");const [rows,setRows]=useState<Pick[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const supplier=suppliers.find((x:any)=>x.id===supplierId);const request=quoteRequests.find((x:any)=>x.id===requestId);const available=useMemo(()=>supplierItems.filter((x:any)=>x.supplier_id===supplierId&&`${x.supplier_item_name} ${x.category}`.toLowerCase().includes(search.toLowerCase())),[supplierItems,supplierId,search]);
  function add(x:any){setRows(old=>[...old,{key:`${x.id}:${Date.now()}`,supplier_catalog_item_id:x.id,catalog_item_id:x.catalog_item_id||null,section_name:x.category||"General",description:x.supplier_item_name,quantity:1,rental_days:request?.start_at&&request?.end_at?Math.max(1,Math.ceil((new Date(request.end_at).getTime()-new Date(request.start_at).getTime())/86400000)):1}]);}
  function patch(key:string,v:Partial<Pick>){setRows(old=>old.map(r=>r.key===key?{...r,...v}:r));}
  async function generate(){if(!supplierId){setMessage("Select a supplier first.");return;}if(!rows.length){setMessage("Add at least one item to the supplier RFQ.");return;}setBusy(true);setMessage("");try{const {data,error}=await supabase.rpc("create_supplier_rfq",{p_supplier_id:supplierId,p_quote_request_id:requestId||null,p_quotation_id:null,p_project_name:request?.project_name||null,p_start_at:request?.start_at||null,p_end_at:request?.end_at||null,p_notes:null,p_items:rows.map((r,i)=>({...r,quote_request_item_id:"",sort_order:i}))});if(error)throw error;const result=data as {supplier_rfq_id:string};location.href=`/admin/supplier-rfqs/${result.supplier_rfq_id}/print?generated=1`;}catch(err){setMessage(err instanceof Error?err.message:"Unable to create supplier RFQ.");setBusy(false);}}
  return <div className="supplierRfqBuilder"><section className="rfqPickPanel"><div className="formGrid"><label>Supplier<select value={supplierId} onChange={e=>{setSupplierId(e.target.value);setRows([])}}><option value="">Choose supplier…</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.company_name}</option>)}</select></label><label>Customer request <small>(optional)</small><select value={requestId} onChange={e=>setRequestId(e.target.value)}><option value="">No linked request</option>{quoteRequests.map((r:any)=><option value={r.id} key={r.id}>{r.request_code} · {r.company_name||r.name||r.project_name||"Untitled"}</option>)}</select></label></div><div className="rfqSupplierSummary">{supplier?<><b>{supplier.company_name}</b><span>{[supplier.contact_name,supplier.phone,supplier.city].filter(Boolean).join(" · ")}</span></>:<span>Select a supplier to load its reusable catalog.</span>}</div>{supplierId&&<><label>Search supplier catalog<input className="rfqSearch" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Equipment name or category"/></label><div className="rfqCatalogResults">{available.map((x:any)=><button type="button" key={x.id} onClick={()=>add(x)}><div><b>{x.supplier_item_name}</b><span>{x.category}</span></div><em>+ Add</em></button>)}{available.length===0&&<p className="formNote">No matching supplier equipment.</p>}</div></>}</section><aside className="rfqCurrentPanel"><div><span>SUPPLIER RFQ</span><h2>{rows.length} requested items</h2></div><div className="rfqSelectedLines">{rows.map((r,i)=><div key={r.key}><span>{i+1}</span><label className="rfqDescriptionLabel">Equipment<input value={r.description} onChange={e=>patch(r.key,{description:e.target.value})}/><small>{r.section_name}</small></label><label>Qty<input type="number" min="0" value={r.quantity} onChange={e=>patch(r.key,{quantity:Number(e.target.value)})}/></label><label>Days<input type="number" min="0" value={r.rental_days} onChange={e=>patch(r.key,{rental_days:Number(e.target.value)})}/></label><button type="button" className="iconButton danger" onClick={()=>setRows(old=>old.filter(x=>x.key!==r.key))} aria-label={`Remove ${r.description||"RFQ item"}`}>×</button></div>)}</div><button className="button gold fullWidthButton" type="button" disabled={busy||!supplierId} onClick={generate}>{busy?"Generating RFQ…":"Generate Supplier RFQ"}</button>{message&&<div className="errorBox" role="status">{message}</div>}</aside>{busy&&<div className="actionOverlay" role="status" aria-live="polite"><div className="actionOverlayCard"><span className="loadingSpinner"/><b>Generating supplier RFQ…</b></div></div>}</div>;
}
