"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";

export function InventoryManager({cameras,accessories}:{cameras:any[];accessories:any[]}){
  const supabase=createClient();const [msg,setMsg]=useState("");const [busy,setBusy]=useState<"camera"|"accessory"|null>(null);
  async function addCamera(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const code=String(f.get("code")||"").trim().toUpperCase();setBusy("camera");setMsg("");try{const {error}=await supabase.from("cameras").insert({camera_code:code,qr_code:`SCH-${code}`,name:String(f.get("name")||"").trim(),manufacturer:String(f.get("manufacturer")||"").trim()||null,model:String(f.get("model")||"").trim()||null,serial_number:String(f.get("serial")||"").trim()||null,current_hours:Number(f.get("hours")||0),location:String(f.get("location")||"Chennai").trim()||"Chennai"});if(error)throw error;location.reload();}catch(err){setMsg(err instanceof Error?err.message:"Unable to add camera.");setBusy(null);}}
  async function addAccessory(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const code=String(f.get("code")||"").trim().toUpperCase();setBusy("accessory");setMsg("");try{const {error}=await supabase.from("accessories").insert({accessory_code:code,qr_code:`SCH-${code}`,name:String(f.get("name")||"").trim(),category:String(f.get("category")||"Accessory").trim()||"Accessory",serial_number:String(f.get("serial")||"").trim()||null,location:String(f.get("location")||"Chennai").trim()||"Chennai"});if(error)throw error;location.reload();}catch(err){setMsg(err instanceof Error?err.message:"Unable to add accessory.");setBusy(null);}}
  return <><div className="adminGrid">
    <form className="adminPanel formPanel" onSubmit={addCamera}><h2>Add camera</h2><label>Camera code<input name="code" required placeholder="CAM-001"/></label><label>Camera name<input name="name" required placeholder="ARRI ALEXA 35"/></label><div className="formGrid"><label>Manufacturer<input name="manufacturer" placeholder="ARRI"/></label><label>Model<input name="model" placeholder="ALEXA 35"/></label></div><label>Serial number<input name="serial"/></label><div className="formGrid"><label>Current camera hours<input name="hours" type="number" min="0" step=".1" defaultValue="0"/></label><label>Location<input name="location" defaultValue="Chennai"/></label></div><button type="submit" className="button gold" disabled={!!busy}>{busy==="camera"?"Adding camera…":"Add camera + QR"}</button></form>
    <form className="adminPanel formPanel" onSubmit={addAccessory}><h2>Add accessory</h2><label>Accessory code<input name="code" required placeholder="ACC-001"/></label><label>Accessory name<input name="name" required placeholder="B-Mount Battery"/></label><div className="formGrid"><label>Category<input name="category" placeholder="Battery"/></label><label>Serial number<input name="serial"/></label></div><label>Location<input name="location" defaultValue="Chennai"/></label><button type="submit" className="button gold" disabled={!!busy}>{busy==="accessory"?"Adding accessory…":"Add accessory + QR"}</button></form>
  </div>{msg&&<div className="errorBox" role="status">{msg}</div>}
  <div className="adminPanel"><h2>QR / RFID registry</h2>{[...cameras,...accessories].map(a=><div className="bookingRow" key={a.id}><div><b>{a.camera_code||a.accessory_code} · {a.name}</b><span>QR: {a.qr_code} · RFID: {a.rfid_tag||"not assigned"}</span></div><em className={`status ${a.status}`}>{a.status}</em></div>)}</div></>;
}
