"use client";import {useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";
export function QuoteManager({requests,rates,cameras,quotations,userId}:{requests:any[];rates:any[];cameras:any[];quotations:any[];userId:string}){
 const supabase=createClient();const [requestId,setRequestId]=useState("");const [discount,setDiscount]=useState(0);const req=requests.find(r=>r.id===requestId);
 const days=req?Math.max(1,Math.ceil((new Date(req.end_at).getTime()-new Date(req.start_at).getTime())/86400000)):1;
 const items=useMemo(()=>{if(!req)return[];return (req.requested_camera_ids||[]).map((id:string)=>{const c=cameras.find(x=>x.id===id);const rate=rates.find(x=>x.camera_id===id);return{id,description:`${c?.camera_code||""} ${c?.name||"Camera"}`,rate:Number(rate?.daily_rate_inr||0)}})},[req,rates,cameras]);
 const subtotal=items.reduce((n,x)=>n+x.rate*days,0);
 async function generate(){if(!req)return;let customerId=null;const {data:cust}=await supabase.from("customers").insert({name:req.name,company_name:req.company_name,phone:req.phone}).select("id").single();customerId=cust?.id||null;
  const {data:q,error}=await supabase.from("quotations").insert({quote_request_id:req.id,customer_id:customerId,subtotal_inr:subtotal,discount_inr:discount,created_by:userId,valid_until:new Date(Date.now()+7*86400000).toISOString().slice(0,10)}).select("id,quotation_code").single();if(error)return alert(error.message);
  if(items.length)await supabase.from("quotation_items").insert(items.map((x,i)=>({quotation_id:q.id,item_type:"camera",item_id:x.id,description:x.description,quantity:1,rental_days:days,unit_rate_inr:x.rate,sort_order:i})));
  await supabase.from("quote_requests").update({status:"quoted"}).eq("id",req.id);location.reload();
 }
 return <><div className="adminGrid"><div className="adminPanel formPanel"><h2>Generate quotation</h2><select value={requestId} onChange={e=>setRequestId(e.target.value)}><option value="">Choose quote request</option>{requests.filter(r=>r.status==="new").map(r=><option key={r.id} value={r.id}>{r.request_code} · {r.company_name||r.name} · {r.project_name}</option>)}</select>{req&&<><p>{new Date(req.start_at).toLocaleString("en-IN")} → {new Date(req.end_at).toLocaleString("en-IN")} · {days} rental day(s)</p>{items.map(x=><div className="bookingRow" key={x.id}><span>{x.description}</span><b>₹{x.rate.toLocaleString("en-IN")}/day</b></div>)}<label>Discount ₹<input type="number" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><div className="quoteTotal"><span>Total</span><b>₹{Math.max(0,subtotal-discount).toLocaleString("en-IN")}</b></div><button className="button gold" type="button" onClick={generate}>Generate quotation</button></>}</div>
 <div className="adminPanel"><h2>Why prices stay private</h2><p>Customer quote requests contain equipment and dates only. Rate cards are readable only by staff/admin.</p></div></div>
 <div className="adminPanel"><h2>Quotation history</h2>{quotations.map(q=><div className="bookingRow" key={q.id}><div><b>{q.quotation_code} · {q.customers?.company_name||q.customers?.name||"Customer"}</b><span>{q.status} · valid to {q.valid_until||"—"}</span></div><strong>₹{Number(q.total_inr||0).toLocaleString("en-IN")}</strong></div>)}</div></>
}
